"use client"
import Bottom from '@/components/Nav/Bottom'
import { Top } from '@/components/Nav/Top'
import Profile from '@/components/Profile/Profile'
import { Card } from '@/components/User/Card'
import { useState } from 'react'
import { GiTaurus } from 'react-icons/gi'
const welcome = () => {
  const [isProfile, setIsProfile] = useState(false);


  return (
    <div>
      {isProfile && <Profile id={1} onClose={() => setIsProfile(false)} />}
      <div className={`mx-5 my-23 lg:flex-wrap lg:flex lg:px-10 lg:gap-5 lg:justify-center lg:my-30${isProfile ? ' lg:blur-lg lg:select-none ' : ''}`}>
        <Card key="1" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="2" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="3" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="4" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="5" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="6" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="7" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="8" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="9" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="10" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="11" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="12" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
        <Card key="13" onclick={() => setIsProfile(true)} name='John Doe, ' age={25} sign={<GiTaurus />} status="connected" verified={true} description='Young 25-year-old man, friendly and always smiling 😊. I enjoy going out with friends, traveling, and discovering new flavors 🍣✈️. Here to meet great people and share good times!' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
      </div>
      <Bottom isProfile={isProfile} />
    </div>
  )
}

export default welcome
