import { Card } from '@/components/User/Card'
import React from 'react'
import { GiTaurus } from 'react-icons/gi'
import { MdVerified } from 'react-icons/md'
import { RiRadioButtonFill } from 'react-icons/ri'

const welcome = () => {
  return (
    <div className='mt-23 mx-5 '>
      <Card key="1" name='John Doe, ' age={25} sign={<GiTaurus />} badges={[<RiRadioButtonFill className='text-green-600' />, <MdVerified className='text-blue-400' />]} description='Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
      <Card key="2" name='John Doe, ' age={25} sign={<GiTaurus />} badges={[<RiRadioButtonFill className='text-green-600' />, <MdVerified className='text-blue-400' />]} description='Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
      <Card key="3" name='John Doe, ' age={25} sign={<GiTaurus />} badges={[<RiRadioButtonFill className='text-green-600' />, <MdVerified className='text-blue-400' />]} description='Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
      <Card key="4" name='John Doe, ' age={25} sign={<GiTaurus />} badges={[<RiRadioButtonFill className='text-green-600' />, <MdVerified className='text-blue-400' />]} description='Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
      <Card key="5" name='John Doe, ' age={25} sign={<GiTaurus />} badges={[<RiRadioButtonFill className='text-green-600' />, <MdVerified className='text-blue-400' />]} description='Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
      <Card key="6" name='John Doe, ' age={25} sign={<GiTaurus />} badges={[<RiRadioButtonFill className='text-green-600' />, <MdVerified className='text-blue-400' />]} description='Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
      <Card key="7" name='John Doe, ' age={25} sign={<GiTaurus />} badges={[<RiRadioButtonFill className='text-green-600' />, <MdVerified className='text-blue-400' />]} description='Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !Hey, wanna chat ? 😉 DM me, we can take a drink or only talk !' img='/img/user/user1.jpg' tags={["Sport", "Music", "Food", "Tv", "Cat", "Sushi", "Work", "Holidays", "Netflix", "Disney", "Computer", "Coffee"]} />
    </div>
  )
}

export default welcome
